sudo: false
language: ruby
env:
  - TEST_DIR=rfvg
script: cd $TEST_DIR && bundle install && bundle exec rake # run the default task
rvm:
  - "2.1"
  - "2.2"
  - "2.3"
  - "ruby-head"
# before_install: 
#   - cd $TEST_DIR && gem install bundler -v 1.14.3
#   - cd $TEST_DIR && bundle install
os:
  - linux
  - osx
matrix:
  allow_failures:
    - os: osx
    - rvm: "2.3" # apparently ruby-2.3 does not exist on travis-ci
    - rvm: ruby-head
